artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/c7e2e1eb9171480882ef264e7e40b519/artifacts
end_time: 1698360283503
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c7e2e1eb9171480882ef264e7e40b519
run_name: intrigued-stag-954
run_uuid: c7e2e1eb9171480882ef264e7e40b519
source_name: ''
source_type: 4
source_version: ''
start_time: 1698360281650
status: 4
tags: []
user_id: omar
