artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/af16d26442584b0b879dd97fad95421d/artifacts
end_time: 1698362842745
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: af16d26442584b0b879dd97fad95421d
run_name: grandiose-fish-895
run_uuid: af16d26442584b0b879dd97fad95421d
source_name: ''
source_type: 4
source_version: ''
start_time: 1698362842736
status: 4
tags: []
user_id: omar
