artifact_location: /home/omar/Documents/Repos/Research/legged_gym/mlFlowLogs/MLFlow_Test/0
creation_time: 1698366102223
experiment_id: '0'
last_update_time: 1698366102223
lifecycle_stage: active
name: Default
