artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/3164c4028000441aad83ee44b2a08bc3/artifacts
end_time: 1698361910932
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3164c4028000441aad83ee44b2a08bc3
run_name: indecisive-bat-243
run_uuid: 3164c4028000441aad83ee44b2a08bc3
source_name: ''
source_type: 4
source_version: ''
start_time: 1698361910924
status: 4
tags: []
user_id: omar
