artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/83f80c158b5f48aba3f62b19ed753baa/artifacts
end_time: 1698362144415
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 83f80c158b5f48aba3f62b19ed753baa
run_name: silent-skunk-879
run_uuid: 83f80c158b5f48aba3f62b19ed753baa
source_name: ''
source_type: 4
source_version: ''
start_time: 1698361942247
status: 4
tags: []
user_id: omar
