artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/5a9d88cde5724481b832eaf85130df4f/artifacts
end_time: 1698358807210
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 5a9d88cde5724481b832eaf85130df4f
run_name: charming-eel-118
run_uuid: 5a9d88cde5724481b832eaf85130df4f
source_name: ''
source_type: 4
source_version: ''
start_time: 1698358805370
status: 4
tags: []
user_id: omar
