artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/8dea206e596f4997ab2fa9f5a9e97df3/artifacts
end_time: 1698361902852
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 8dea206e596f4997ab2fa9f5a9e97df3
run_name: resilient-bee-907
run_uuid: 8dea206e596f4997ab2fa9f5a9e97df3
source_name: ''
source_type: 4
source_version: ''
start_time: 1698361902843
status: 4
tags: []
user_id: omar
