artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/778ccd35baf7402080e7a1968c34e305/artifacts
end_time: 1698361923153
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 778ccd35baf7402080e7a1968c34e305
run_name: skillful-fowl-935
run_uuid: 778ccd35baf7402080e7a1968c34e305
source_name: ''
source_type: 4
source_version: ''
start_time: 1698361923145
status: 4
tags: []
user_id: omar
