artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/889034aac35e4dcfb10aaa1c1c4bed55/artifacts
end_time: 1698361886460
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 889034aac35e4dcfb10aaa1c1c4bed55
run_name: suave-conch-776
run_uuid: 889034aac35e4dcfb10aaa1c1c4bed55
source_name: ''
source_type: 4
source_version: ''
start_time: 1698361886450
status: 4
tags: []
user_id: omar
