artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/mlFlowLogs/MLFlow_Test/0/6fc0e2ec8fa54070a2e9233374777df9/artifacts
end_time: 1698364462799
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6fc0e2ec8fa54070a2e9233374777df9
run_name: secretive-snipe-890
run_uuid: 6fc0e2ec8fa54070a2e9233374777df9
source_name: ''
source_type: 4
source_version: ''
start_time: 1698363160304
status: 4
tags: []
user_id: omar
