artifact_uri: /home/omar/Documents/Repos/Research/legged_gym/legged_gym/mlFlowLogs/MLFlow_Test/0/d62876b06c704990b76263eae53c403e/artifacts
end_time: 1698360894969
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d62876b06c704990b76263eae53c403e
run_name: charming-crow-372
run_uuid: d62876b06c704990b76263eae53c403e
source_name: ''
source_type: 4
source_version: ''
start_time: 1698360879546
status: 4
tags: []
user_id: omar
